terraform {
  cloud {
    # TODO: Replace with your Terraform Cloud organization name
    organization = "venatio-infra"

    workspaces {
      name = "proxy-scanner"
    }
  }

  required_version = ">= 1.6"

  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 3.0"
    }
  }
}

# OpenStack provider — credentials come from Terraform Cloud environment variables:
#   OS_AUTH_URL, OS_TENANT_ID, OS_TENANT_NAME, OS_USERNAME, OS_PASSWORD, OS_REGION_NAME
provider "openstack" {}

# ---------------------------------------------------------------------------
# Data sources
# ---------------------------------------------------------------------------

# Look up the Ubuntu 24.04 image dynamically (OVH naming can vary by region)
data "openstack_images_image_v2" "ubuntu" {
  name_regex  = "^Ubuntu 24\\.04"
  most_recent = true
}

# ---------------------------------------------------------------------------
# SSH keypair (generated by Terraform)
# ---------------------------------------------------------------------------

resource "openstack_compute_keypair_v2" "proxy_scanner" {
  name = var.ssh_key_name
}

# ---------------------------------------------------------------------------
# Security group — use the default security group
# ---------------------------------------------------------------------------
# OVH has a low security group quota. The default security group already
# allows all egress. We just add SSH ingress rules to it.

data "openstack_networking_secgroup_v2" "default" {
  name = "default"
}

resource "openstack_networking_secgroup_rule_v2" "ssh_ipv4" {
  security_group_id = data.openstack_networking_secgroup_v2.default.id
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 22
  port_range_max    = 22
  remote_ip_prefix  = "0.0.0.0/0"
}

resource "openstack_networking_secgroup_rule_v2" "ssh_ipv6" {
  security_group_id = data.openstack_networking_secgroup_v2.default.id
  direction         = "ingress"
  ethertype         = "IPv6"
  protocol          = "tcp"
  port_range_min    = 22
  port_range_max    = 22
  remote_ip_prefix  = "::/0"
}

# ---------------------------------------------------------------------------
# Compute instance
# ---------------------------------------------------------------------------

resource "openstack_compute_instance_v2" "proxy_scanner" {
  name        = "proxy-scanner"
  flavor_name = var.flavor
  image_id    = data.openstack_images_image_v2.ubuntu.id
  key_pair    = openstack_compute_keypair_v2.proxy_scanner.name

  security_groups = [
    data.openstack_networking_secgroup_v2.default.name,
  ]

  user_data = templatefile("${path.module}/cloud-init.yaml", {
    compose_file = indent(6, file("${path.root}/../docker-compose.yml"))
  })

  network {
    name = "Ext-Net"
  }

  metadata = {
    managed_by = "terraform"
    project    = "proxy-scanner"
  }
}
