apiVersion: v1
kind: Service
metadata:
  name: proxy-api
  namespace: proxy-scanner
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: proxy-scanner
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: proxy-scanner
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
